const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const repoRoot = path.resolve(__dirname, '../../..');
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');

const localSync = read('packages/git/src/local_repo_sync.js');
const workflow = read('packages/temporal/src/workflows/hostAgentWorkflow.js');
const workflowIndex = read('packages/temporal/src/workflows/index.js');
const worker = read('packages/host-agent/src/worker.js');
const activities = read('packages/host-agent/src/activities.js');
const dockerEventBridge = read('packages/host-agent/src/dockerEventBridge.js');
const dockerTelemetryBridge = read('packages/host-agent/src/dockerTelemetryBridge.js');
const dockerResource = read('packages/host-agent/src/dockerResource.js');
const migration = read('packages/db_build/src/migrations/00100__host_agent_local_repository_sync.sql');
const packageJson = JSON.parse(read('package.json'));
const envExample = read('.env.example');

assert.match(localSync, /skyCommandHostAgentToolWorkflow/);
assert.match(localSync, /SKYCOMMAND_HOST_AGENT_ENABLED/);
assert.match(localSync, /temporal_host_agent/);
assert.match(workflow, /isDockerDetail/);
assert.match(workflow, /'45 seconds'/);
assert.match(workflow, /'3 minutes'/);
assert.match(workflow, /taskQueue:\s*hostTaskQueue/);
assert.match(workflowIndex, /hostAgentWorkflow/);
assert.match(worker, /SkyCommand Host Agent refuses Docker execution/);
assert.match(worker, /SKYCOMMAND_DEV_COMMIT_PROFILE/);
assert.match(worker, /worker\.temporal_worker_heartbeats/);
assert.match(worker, /skycommand-host-agent-heartbeat/);
assert.match(worker, /Heartbeat persistence recovered/);
assert.match(worker, /PostgreSQL will be retried automatically/);
assert.match(worker, /startDockerEventBridge/);
assert.match(worker, /startDockerTelemetryBridge/);
assert.match(activities, /DEV_COMMIT_TOOL_CODE/);
assert.match(activities, /executeDevCommit/);
assert.match(activities, /orchestratedExecution:\s*true/);
assert.match(activities, /executionTarget:\s*'HOST'/);
assert.match(activities, /LOCAL_REPOSITORY_SYNC_TOOL_CODE/);
assert.match(activities, /DOCKER_SNAPSHOT_TOOL_CODE/);
assert.match(activities, /DOCKER_COMPOSE_CONTROL_TOOL_CODE/);
assert.match(activities, /DOCKER_CONTAINER_DETAIL_TOOL_CODE/);
assert.match(activities, /DOCKER_CONTAINER_CONTROL_TOOL_CODE/);
assert.match(activities, /DOCKER_RESOURCE_DETAIL_TOOL_CODE/);
assert.match(activities, /DOCKER_RESOURCE_CONTROL_TOOL_CODE/);
assert.match(activities, /executeDockerSnapshot/);
assert.match(activities, /executeDockerComposeControl/);
assert.match(activities, /executeDockerContainerDetail/);
assert.match(activities, /executeDockerContainerControl/);
assert.match(activities, /executeDockerResourceDetail/);
assert.match(activities, /executeDockerResourceControl/);
assert.match(activities, /SKYCOMMAND_HOST_AGENT_TOOL_NOT_ALLOWED/);
assert.match(dockerEventBridge, /docker.*events/i);
assert.match(dockerEventBridge, /X-SkyCommand-Internal-Token/);
assert.match(dockerEventBridge, /ALLOWED_DOCKER_CONTAINER_EVENT_ACTIONS/);
assert.doesNotMatch(dockerEventBridge, /docker exec/i);
assert.match(dockerTelemetryBridge, /\['stats', '--no-stream'/);
assert.match(dockerTelemetryBridge, /\['inspect', '--format'/);
assert.match(dockerTelemetryBridge, /DOCKER_TELEMETRY_SNAPSHOT/);
assert.doesNotMatch(dockerTelemetryBridge, /Config\?\.Env|environment:/i);
assert.match(dockerResource, /DATA_PROTECTED/);
assert.match(dockerResource, /SYSTEM_PROTECTED/);
assert.match(dockerResource, /GUARDED_REMOVE/);
assert.doesNotMatch(dockerResource, /--force|\b-f\b/);
assert.match(migration, /'admin-web'/);
assert.match(migration, /'api'/);
assert.match(migration, /'worker'/);
assert.match(migration, /local_repo_sync/);
assert.equal(packageJson.scripts['host-agent'], 'node packages/host-agent/src/worker.js');
assert.equal(packageJson.scripts['host-agent:check'], 'node packages/host-agent/src/health.js');
assert.match(envExample, /SKYCOMMAND_HOST_AGENT_ENABLED=false/);
assert.match(envExample, /SKYCOMMAND_HOST_AGENT_TASK_QUEUE=skycommand-host-local/);
assert.match(envExample, /SKYCOMMAND_HOST_AGENT_HEARTBEAT_DB_CONNECT_TIMEOUT_MS=3000/);
assert.match(envExample, /SKYCOMMAND_DOCKER_TARGET_CODE=LOCAL_DOCKER/);
assert.match(envExample, /SKYCOMMAND_DOCKER_COMMAND_TIMEOUT_MS=10000/);
assert.match(envExample, /SKYCOMMAND_DOCKER_CONTROL_TIMEOUT_MS=120000/);
assert.match(envExample, /SKYCOMMAND_DOCKER_CONTAINER_TIMEOUT_MS=30000/);
assert.match(envExample, /SKYCOMMAND_DOCKER_RESOURCE_TIMEOUT_MS=30000/);
assert.match(envExample, /SKYCOMMAND_DOCKER_SELF_PROJECT_NAME=skycommand/);
assert.match(envExample, /SKYCOMMAND_DOCKER_EVENT_STREAM_ENABLED=true/);
assert.match(envExample, /SKYCOMMAND_DOCKER_EVENT_HEARTBEAT_MS=15000/);
assert.match(envExample, /SKYCOMMAND_DOCKER_TELEMETRY_ENABLED=true/);
assert.match(envExample, /SKYCOMMAND_DOCKER_TELEMETRY_INTERVAL_MS=5000/);

console.log('✅ SkyCommand Host Agent self-test passed.');
