const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const sourceRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(sourceRoot, '../../..');
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');

const navbar = read('apps/admin-web/src/components/Navbar.jsx');
const router = read('apps/admin-web/src/main.jsx');
const overview = read('apps/admin-web/src/pages/DockerOverview.jsx');
const eventHook = read('apps/admin-web/src/hooks/useDockerEventStream.js');
const telemetryHook = read('apps/admin-web/src/hooks/useDockerTelemetryStream.js');
const telemetryVisuals = read('apps/admin-web/src/components/charts/DockerTelemetryVisuals.jsx');
const liveStatus = read('apps/admin-web/src/utils/dockerLiveStatus.js');
const echartCanvas = read('apps/admin-web/src/components/charts/EChartCanvas.jsx');
const apiClient = read('apps/admin-web/src/services/api.js');
const inventory = read('apps/admin-web/src/pages/DockerInventory.jsx');
const operations = read('apps/admin-web/src/pages/DockerOperations.jsx');
const containerDetails = read('apps/admin-web/src/components/DockerContainerDetailsModal.jsx');
const projectDetails = read('apps/admin-web/src/components/DockerProjectDetailsModal.jsx');
const resourceDetails = read('apps/admin-web/src/components/DockerResourceDetailsModal.jsx');
const webService = read('apps/admin-web/src/services/infrastructureService.js');
const apiRoutes = read('apps/api/src/routes/infrastructure.routes.js');
const eventStreamService = read('apps/api/src/services/dockerEventStreamService.js');
const telemetryStreamService = read('apps/api/src/services/dockerTelemetryStreamService.js');
const nginx = read('docker/web.nginx.conf');
const apiServer = read('apps/api/src/server.js');
const service = read('apps/api/src/services/infrastructureService.js');
const activities = read('packages/host-agent/src/activities.js');
const readMigration = read('packages/db_build/src/migrations/00102__docker_infrastructure_read_foundation.sql');
const controlMigration = read('packages/db_build/src/migrations/00103__docker_compose_lifecycle_controls.sql');
const containerMigration = read('packages/db_build/src/migrations/00104__docker_container_operations.sql');
const resourceMigration = read('packages/db_build/src/migrations/00105__docker_resource_cleanup.sql');

assert.match(navbar, /label: 'Docker'/);
assert.doesNotMatch(navbar, /label: 'Docker Overview'/);
assert.match(navbar, /label: 'Projects'/);
assert.match(navbar, /projects: '\/docker\/projects'/);
assert.match(navbar, /label: 'Containers'/);
assert.match(navbar, /label: 'Images'/);
assert.match(navbar, /label: 'Storage'/);
assert.match(navbar, /label: 'Networks'/);
assert.match(navbar, /networks: '\/docker\/networks'/);
assert.match(navbar, /label: 'Docker Operations'/);
const dashboardGroup = navbar.slice(
  navbar.indexOf("label: 'Dashboards'"),
  navbar.indexOf("label: 'Tools',\n      icon: '◧'"),
);
assert.match(dashboardGroup, /label: 'Docker'[\s\S]*?to: '\/docker\/overview'/);
const dockerGroup = navbar.slice(
  navbar.indexOf("label: 'Docker',\n      icon: '⬡'"),
  navbar.indexOf("label: 'Access Control'"),
);
assert.ok(
  dockerGroup.indexOf("label: 'Docker Operations'") < dockerGroup.indexOf("label: 'Projects'"),
  'Docker Operations should be the first item in the Docker menu category.',
);
assert.match(navbar, /INFRASTRUCTURE_DOCKER_READ/);
assert.match(router, /path="docker\/overview"/);
assert.match(router, /path="docker\/projects"/);
assert.match(router, /path="docker\/containers"/);
assert.match(router, /path="docker\/images"/);
assert.match(router, /path="docker\/storage"/);
assert.match(router, /path="docker\/networks"/);
assert.match(router, /path="docker\/operations"/);
assert.match(overview, /SkyCommand Host Agent/);
assert.match(overview, /Compose Projects/);
assert.match(overview, /Docker Event Stream/);
assert.match(overview, /Live Observability/);
assert.match(overview, /DockerTelemetryVisuals/);
assert.match(overview, /Failure domain/);
assert.match(overview, /Docker source/);
assert.match(overview, /sourceErrorCode/);
assert.match(eventHook, /streamDockerEvents/);
assert.match(eventHook, /CONNECTED/);
assert.match(telemetryHook, /streamDockerTelemetry/);
assert.match(telemetryHook, /MAX_VISIBLE_DOCKER_TELEMETRY_SAMPLES/);
assert.match(telemetryVisuals, /Docker Runtime Pressure/);
assert.match(telemetryVisuals, /CPU Utilization/);
assert.match(telemetryVisuals, /Memory Pressure/);
assert.match(telemetryVisuals, /I\/O Throughput/);
assert.match(telemetryVisuals, /Current Resource Leaders/);
assert.match(telemetryVisuals, /Historical sample retained/);
assert.match(telemetryVisuals, /sourceErrorCode/);
assert.match(telemetryVisuals, /getDockerLiveLaneState/);
assert.match(liveStatus, /last received values remain visible for diagnosis/);
assert.match(liveStatus, /STALE/);
assert.match(liveStatus, /DEGRADED/);
assert.match(echartCanvas, /replaceMerge: \['series'\]/);
assert.match(echartCanvas, /instance\.setOption\(normalizedOption/);
assert.match(apiClient, /text\/event-stream/);
assert.match(apiClient, /Last-Event-ID/);
assert.match(inventory, /INFRASTRUCTURE_DOCKER_CONTROL/);
assert.match(inventory, /DOCKER_BROWSER_PAGE_SIZE = 10/);
assert.match(inventory, /dockerProjectSearch/);
assert.match(inventory, /dockerProjectStateFilter/);
assert.match(inventory, /dockerProjectStatusFilter/);
assert.match(inventory, /dockerProjectPageSelect/);
assert.match(inventory, /pagedProjects\[0\]/);
assert.match(inventory, /selectedProjectName/);
assert.match(inventory, /useSearchParams/);
assert.match(inventory, /searchParams\.get\('q'\)/);
assert.match(inventory, /searchParams\.get\('project'\)/);
assert.match(inventory, /dockerContainerSearch/);
assert.match(inventory, /dockerContainerProjectFilter/);
assert.match(inventory, /dockerContainerStateFilter/);
assert.match(inventory, /dockerContainerPageSelect/);
assert.match(inventory, /dockerImageSearch/);
assert.match(inventory, /dockerImageRepositoryFilter/);
assert.match(inventory, /dockerImageUsageFilter/);
assert.match(inventory, /dockerImagePageSelect/);
assert.match(inventory, /Clear filters/);
assert.match(inventory, /sky-selected-row/);
assert.match(inventory, /pagedContainers\[0\]/);
assert.match(inventory, /pagedImages\[0\]/);
assert.match(inventory, /embedded/);
assert.match(inventory, /DockerProjectDetailsModal/);
assert.match(inventory, /embedded/);
const projectTableSource = inventory.slice(
  inventory.indexOf('function ProjectTable'),
  inventory.indexOf('function ContainerTable'),
);
assert.match(projectTableSource, /sky-selected-row/);
assert.doesNotMatch(projectTableSource, /<th>Controls<\/th>/);
assert.doesNotMatch(projectTableSource, /<th>Actions<\/th>/);
assert.doesNotMatch(projectTableSource, /Project Details/);
const storageTableSource = inventory.slice(
  inventory.indexOf('function StorageTable'),
  inventory.indexOf('function NetworkTable'),
);
assert.match(storageTableSource, /sky-selected-row/);
assert.doesNotMatch(storageTableSource, /<th>Actions<\/th>/);
assert.doesNotMatch(storageTableSource, /Volume Details/);
const networkTableSource = inventory.slice(
  inventory.indexOf('function NetworkTable'),
  inventory.indexOf('function DockerInventory'),
);
assert.match(networkTableSource, /sky-selected-row/);
assert.doesNotMatch(networkTableSource, /<th>Actions<\/th>/);
assert.doesNotMatch(networkTableSource, /Network Details/);
assert.match(inventory, /controlDockerContainer/);
assert.match(inventory, /INFRASTRUCTURE_DOCKER_CLEANUP/);
assert.match(inventory, /dockerStorageSearch/);
assert.match(inventory, /dockerStorageDriverFilter/);
assert.match(inventory, /dockerStorageScopeFilter/);
assert.match(inventory, /dockerStoragePageSelect/);
assert.match(inventory, /pagedVolumes\[0\]/);
assert.match(inventory, /dockerNetworkSearch/);
assert.match(inventory, /dockerNetworkDriverFilter/);
assert.match(inventory, /dockerNetworkCleanupFilter/);
assert.match(inventory, /dockerNetworkPageSelect/);
assert.match(inventory, /pagedNetworks\[0\]/);
assert.match(resourceDetails, /Storage Details/);
assert.match(resourceDetails, /Network Details/);
assert.match(resourceDetails, /Selected storage workspace/);
assert.match(resourceDetails, /Selected network workspace/);
assert.match(inventory, /Data protected/);
assert.match(inventory, /System protected/);
assert.match(inventory, /Failure domain/);
assert.match(inventory, /Docker provider/);
assert.match(operations, /Docker operation history/);
assert.match(operations, /dockerOperationSearch/);
assert.match(operations, /dockerOperationScope/);
assert.match(operations, /dockerOperationAction/);
assert.match(operations, /dockerOperationResult/);
assert.match(operations, /dockerOperationsPageSelect/);
const operationsTableSource = operations.slice(
  operations.indexOf('<thead>'),
  operations.indexOf('</table>') + '</table>'.length,
);
assert.match(operationsTableSource, /<th>Resource<\/th>[\s\S]*?<th>Requested<\/th>[\s\S]*?<th>Project<\/th>[\s\S]*?<th>Type<\/th>/);
assert.doesNotMatch(operationsTableSource, /<th>Scope<\/th>/);
assert.match(operations, /function formatResourceType\(resourceType\)/);
assert.match(operations, /COMPOSE_PROJECT'\) return 'Project'/);
assert.match(operationsTableSource, /formatResourceType\(item\.resourceType\)/);
assert.match(operations, /function getResourceDrilldown\(item\)/);
assert.match(operations, /`\/docker\/projects\?\$\{params\.toString\(\)\}`/);
assert.match(operations, /`\/docker\/containers\?\$\{params\.toString\(\)\}`/);
assert.match(operations, /`\/docker\/images\?\$\{params\.toString\(\)\}`/);
assert.match(operations, /`\/docker\/networks\?\$\{params\.toString\(\)\}`/);
assert.match(operationsTableSource, /<Link/);
assert.match(operationsTableSource, /to=\{resourceDrilldown\}/);
assert.doesNotMatch(operationsTableSource, /label=\{item\.resourceType/);
assert.match(operations, /First/);
assert.match(operations, /Back/);
assert.match(operations, /Next/);
assert.match(operations, /Last/);
assert.match(operations, /Clear filters/);
assert.match(operations, /PAGE_SIZE = 10/);
assert.doesNotMatch(operations, /Operation Filters/);
assert.doesNotMatch(operations, />\s*Apply\s*</);
assert.doesNotMatch(operations, /Control Plane Guardrail/);
assert.doesNotMatch(operations, /Lifecycle Control Policy/);
assert.match(operations, /Compose project/);
assert.match(operations, /Container/);
assert.match(operations, /Pause/);
assert.match(operations, /Unpause/);
assert.match(operations, /Remove/);
assert.doesNotMatch(operations, /docker exec/i);
assert.match(containerDetails, /Selected container workspace/);
assert.match(containerDetails, /Container Details/);
assert.match(containerDetails, /embedded/);
assert.match(containerDetails, /Environment redacted/);
assert.match(containerDetails, /Container Logs/);
assert.match(containerDetails, /Start/);
assert.match(containerDetails, /Stop/);
assert.match(containerDetails, /Restart/);
assert.match(containerDetails, /Pause/);
assert.match(containerDetails, /Unpause/);
assert.doesNotMatch(containerDetails, /docker exec/i);
assert.match(projectDetails, /Docker workload details/);
assert.match(projectDetails, /Selected project workspace/);
assert.match(projectDetails, /Project Details/);
assert.match(projectDetails, /embedded = false/);
assert.match(projectDetails, /Workload CPU/);
assert.match(projectDetails, /Workload Memory/);
assert.match(projectDetails, /Project Containers/);
assert.match(projectDetails, /Recent Docker Activity/);
assert.match(projectDetails, /useDockerEventStream/);
assert.match(projectDetails, /useDockerTelemetryStream/);
assert.match(projectDetails, /Compose Lifecycle/);
assert.match(projectDetails, /Start/);
assert.match(projectDetails, /Stop/);
assert.match(projectDetails, /Restart/);
assert.match(projectDetails, /Self-managed/);
assert.match(projectDetails, /Live signal degraded/);
assert.match(projectDetails, /getDockerLiveLaneState/);
assert.doesNotMatch(projectDetails, /docker exec/i);
assert.match(resourceDetails, /Selected image workspace/);
assert.match(resourceDetails, /Image Details/);
assert.match(resourceDetails, /embedded/);
assert.match(resourceDetails, /Cleanup Policy/);
assert.match(resourceDetails, /Data protected/);
assert.match(resourceDetails, /System protected/);
assert.match(resourceDetails, /Remove unused image/);
assert.match(resourceDetails, /Remove unused network/);
assert.doesNotMatch(resourceDetails, /--force|docker exec/i);
assert.match(webService, /providers\/docker\/projects/);
assert.match(webService, /providers\/docker\/operations/);
assert.match(webService, /providers\/docker\/containers/);
assert.match(webService, /controlDockerContainer/);
assert.match(webService, /getDockerContainerDetail/);
assert.match(webService, /getDockerResourceDetail/);
assert.match(webService, /controlDockerResource/);
assert.match(webService, /streamDockerEvents/);
assert.match(webService, /streamDockerTelemetry/);
assert.match(apiRoutes, /providers\/docker\/events\/ingest/);
assert.match(apiRoutes, /providers\/docker\/events\/stream/);
assert.match(apiRoutes, /providers\/docker\/telemetry\/ingest/);
assert.match(apiRoutes, /providers\/docker\/telemetry\/stream/);
assert.match(eventStreamService, /BRIDGE_HEARTBEAT/);
assert.match(eventStreamService, /text\/event-stream/);
assert.match(eventStreamService, /MAX_DOCKER_EVENT_BUFFER/);
assert.match(telemetryStreamService, /MAX_DOCKER_TELEMETRY_BUFFER/);
assert.match(telemetryStreamService, /networkRxRateBytesPerSec/);
assert.match(telemetryStreamService, /text\/event-stream/);
assert.match(nginx, /docker\/events\/stream/);
assert.match(nginx, /docker\/telemetry\/stream/);
assert.match(nginx, /proxy_buffering off/);
assert.match(apiRoutes, /providers\/docker\/overview/);
assert.match(apiRoutes, /providers\/docker\/operations/);
assert.match(apiRoutes, /providers\/docker\/containers\/:containerId/);
assert.match(apiRoutes, /providers\/docker\/images\/:resourceReference/);
assert.match(apiRoutes, /providers\/docker\/volumes\/:resourceReference/);
assert.match(apiRoutes, /providers\/docker\/networks\/:resourceReference/);
assert.match(apiRoutes, /INFRASTRUCTURE_DOCKER_CLEANUP/);
assert.match(apiRoutes, /INFRASTRUCTURE_DOCKER_CONTROL/);
assert.equal(apiRoutes.includes('/providers/docker/volumes/:resourceReference/actions'), false);
assert.match(apiServer, /app\.use\('\/api\/infrastructure', infrastructureRoutes\)/);
assert.match(service, /DOCKER_COMPOSE_CONTROL_TOOL_CODE/);
assert.match(service, /DOCKER_CONTAINER_DETAIL_TOOL_CODE/);
assert.match(service, /DOCKER_CONTAINER_CONTROL_TOOL_CODE/);
assert.match(service, /DOCKER_RESOURCE_DETAIL_TOOL_CODE/);
assert.match(service, /DOCKER_RESOURCE_CONTROL_TOOL_CODE/);
assert.match(service, /DOCKER_RESOURCE_CONTROL/);
assert.match(service, /DOCKER_CONTAINER_CONTROL/);
assert.match(service, /SKYCOMMAND_DOCKER_SELF_CONTROL_BLOCKED/);
assert.match(service, /DOCKER_COMPOSE_CONTROL/);
assert.match(activities, /executeDockerComposeControl/);
assert.match(activities, /executeDockerContainerDetail/);
assert.match(activities, /executeDockerContainerControl/);
assert.match(activities, /executeDockerResourceDetail/);
assert.match(activities, /executeDockerResourceControl/);
assert.match(readMigration, /INFRASTRUCTURE_DOCKER_READ/);
assert.match(controlMigration, /INFRASTRUCTURE_DOCKER_CONTROL/);
assert.match(controlMigration, /Start, stop, and restart/i);
assert.match(containerMigration, /container deep inspection/i);
assert.match(containerMigration, /INFRASTRUCTURE_DOCKER_READ/);
assert.match(containerMigration, /INFRASTRUCTURE_DOCKER_CONTROL/);
assert.match(resourceMigration, /INFRASTRUCTURE_DOCKER_CLEANUP/);
assert.match(resourceMigration, /Persistent volume deletion is not exposed/i);
assert.match(resourceMigration, /SUPER_ADMIN/);

console.log('✅ SkyCommand Docker infrastructure UI self-test passed.');
