const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const sourceRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(sourceRoot, '../../..');
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');

const navbar = read('apps/admin-web/src/components/Navbar.jsx');
const router = read('apps/admin-web/src/main.jsx');
const overview = read('apps/admin-web/src/pages/DockerOverview.jsx');
const inventory = read('apps/admin-web/src/pages/DockerInventory.jsx');
const operations = read('apps/admin-web/src/pages/DockerOperations.jsx');
const webService = read('apps/admin-web/src/services/infrastructureService.js');
const apiRoutes = read('apps/api/src/routes/infrastructure.routes.js');
const apiServer = read('apps/api/src/server.js');
const service = read('apps/api/src/services/infrastructureService.js');
const activities = read('packages/host-agent/src/activities.js');
const readMigration = read('packages/db_build/src/migrations/00102__docker_infrastructure_read_foundation.sql');
const controlMigration = read('packages/db_build/src/migrations/00103__docker_compose_lifecycle_controls.sql');

assert.match(navbar, /label: 'Docker'/);
assert.match(navbar, /label: 'Docker Overview'/);
assert.match(navbar, /label: 'Compose Projects'/);
assert.match(navbar, /label: 'Containers'/);
assert.match(navbar, /label: 'Images'/);
assert.match(navbar, /label: 'Storage & Networks'/);
assert.match(navbar, /label: 'Docker Operations'/);
assert.match(navbar, /INFRASTRUCTURE_DOCKER_READ/);
assert.match(router, /path="docker\/overview"/);
assert.match(router, /path="docker\/projects"/);
assert.match(router, /path="docker\/containers"/);
assert.match(router, /path="docker\/images"/);
assert.match(router, /path="docker\/storage"/);
assert.match(router, /path="docker\/operations"/);
assert.match(overview, /SkyCommand Host Agent/);
assert.match(overview, /Compose Projects/);
assert.match(inventory, /INFRASTRUCTURE_DOCKER_CONTROL/);
assert.match(inventory, /Start/);
assert.match(inventory, /Stop/);
assert.match(inventory, /Restart/);
assert.match(inventory, /Self-managed/);
assert.match(operations, /Docker Operation History/);
assert.match(operations, /Self-project protected/);
assert.doesNotMatch(operations, /docker exec/i);
assert.match(webService, /providers\/docker\/projects/);
assert.match(webService, /providers\/docker\/operations/);
assert.match(apiRoutes, /providers\/docker\/overview/);
assert.match(apiRoutes, /providers\/docker\/operations/);
assert.match(apiRoutes, /INFRASTRUCTURE_DOCKER_CONTROL/);
assert.match(apiServer, /app\.use\('\/api\/infrastructure', infrastructureRoutes\)/);
assert.match(service, /DOCKER_COMPOSE_CONTROL_TOOL_CODE/);
assert.match(service, /SKYCOMMAND_DOCKER_SELF_CONTROL_BLOCKED/);
assert.match(service, /DOCKER_COMPOSE_CONTROL/);
assert.match(activities, /executeDockerComposeControl/);
assert.match(readMigration, /INFRASTRUCTURE_DOCKER_READ/);
assert.match(controlMigration, /INFRASTRUCTURE_DOCKER_CONTROL/);
assert.match(controlMigration, /Start, stop, and restart/i);

console.log('✅ SkyCommand Docker infrastructure UI self-test passed.');
