-- ============================================================
-- Migration: 00071__api_request_telemetry.sql
-- Purpose:
-- Adds persistent, privacy-conscious HTTP request telemetry for
-- SkyCommand API observability dashboards and operational analysis.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS core;

CREATE TABLE IF NOT EXISTS core.api_request_telemetry (
  telemetry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  method TEXT NOT NULL,
  route_template TEXT NOT NULL,
  status_code INTEGER NOT NULL,
  duration_ms NUMERIC(14, 3) NOT NULL DEFAULT 0,
  app_code TEXT,
  auth_mode TEXT NOT NULL DEFAULT 'ANONYMOUS',
  request_bytes BIGINT NOT NULL DEFAULT 0,
  response_bytes BIGINT NOT NULL DEFAULT 0,
  request_id TEXT NOT NULL,
  CONSTRAINT api_request_telemetry_method_check
    CHECK (method = UPPER(method) AND char_length(method) BETWEEN 1 AND 16),
  CONSTRAINT api_request_telemetry_status_code_check
    CHECK (status_code BETWEEN 100 AND 599),
  CONSTRAINT api_request_telemetry_duration_check
    CHECK (duration_ms >= 0),
  CONSTRAINT api_request_telemetry_request_bytes_check
    CHECK (request_bytes >= 0),
  CONSTRAINT api_request_telemetry_response_bytes_check
    CHECK (response_bytes >= 0),
  CONSTRAINT api_request_telemetry_request_id_length_check
    CHECK (char_length(request_id) BETWEEN 1 AND 128)
);

ALTER TABLE core.api_request_telemetry OWNER TO postgres;

COMMENT ON TABLE core.api_request_telemetry IS
  'Normalized SkyCommand API request evidence. Stores route templates and operational measurements only; headers, tokens, bodies, query values, passwords, and secrets are deliberately excluded.';
COMMENT ON COLUMN core.api_request_telemetry.route_template IS
  'Normalized Express route template or privacy-safe fallback path. Raw query strings and high-cardinality identifiers are not retained.';
COMMENT ON COLUMN core.api_request_telemetry.app_code IS
  'Authenticated application scope when known, such as SKYSERVER_ADMIN or SKYWEB.';
COMMENT ON COLUMN core.api_request_telemetry.auth_mode IS
  'Authentication mode observed after request processing, such as BEARER_SESSION, INTERNAL_SERVICE_TOKEN, or ANONYMOUS.';
COMMENT ON COLUMN core.api_request_telemetry.request_id IS
  'Bounded correlation identifier returned in the X-Request-Id response header.';

CREATE INDEX IF NOT EXISTS ix_api_request_telemetry_occurred_at
  ON core.api_request_telemetry (occurred_at DESC);

CREATE INDEX IF NOT EXISTS ix_api_request_telemetry_route_time
  ON core.api_request_telemetry (route_template, occurred_at DESC);

CREATE INDEX IF NOT EXISTS ix_api_request_telemetry_status_time
  ON core.api_request_telemetry (status_code, occurred_at DESC);

CREATE INDEX IF NOT EXISTS ix_api_request_telemetry_app_time
  ON core.api_request_telemetry (app_code, occurred_at DESC)
  WHERE app_code IS NOT NULL;
