const DEVELOPMENT_PROMOTION_TOOL_PERMISSION_CODES = Object.freeze([
  'DEV_PROMOTION_PREFLIGHT',
  'CAPABILITY_CATALOG_EXPORT',
  'REPO_MAP_GENERATE',
  'REPO_ZIP_GENERATE',
]);

const DEVELOPMENT_PROMOTION_REQUIRED_PERMISSION_CODES = Object.freeze([
  'WORKFLOW_RUN',
  ...DEVELOPMENT_PROMOTION_TOOL_PERMISSION_CODES,
  'GIT_COMMIT_RUN',
  'GIT_DEV_PR_MERGE_RUN',
  'GIT_MAIN_MERGE_RUN',
  'GIT_LOCAL_SYNC_RUN',
  'CORE_RUN_LOW_RISK_SCRIPT',
  'CORE_RUN_MEDIUM_RISK_SCRIPT',
  'CORE_RUN_HIGH_RISK_SCRIPT',
]);

module.exports = {
  DEVELOPMENT_PROMOTION_REQUIRED_PERMISSION_CODES,
  DEVELOPMENT_PROMOTION_TOOL_PERMISSION_CODES,
};
